#!/bin/bash

read -p "Enter a number: " NUM
echo

if [ $NUM -gt 100 ]
then
   echo "We have entered in IF block."
   sleep 3
   echo "Your Number is greater than 100"
   echo
   date
fi


echo "Script execution completed successfully."

##############################################################

#!/bin/bash

read -p "Enter a number: " NUM
echo

if [ $NUM -gt 100 ]
then
   echo "We have entered in IF block."
   sleep 3
   echo "Your Number is greater than 100"
   echo
   date
else
  echo "You have entered number less than 100."
fi


echo "Script execution completed successfully."


########################################################################


#!/bin/bash

value=$(ip addr show | grep -v LOOPBACK | grep -ic mtu)  
# grep -v is selecting all , leaving LOOPBACK
# grep -ic -> count , case in-sensitive

if [ $value -eq 1 ]
then
  echo "1 Active Network Interface found."
elif [ $value -gt 1 ]
then
  echo "Found Multiple active Interface."
else
  echo "No Active interface found."
fi

